import { Component, OnInit } from '@angular/core';
import  { trigger, state, style, transition, animate } from '@angular/animations';

@Component({
  selector: 'app-faq',
  templateUrl: './faq.component.html',
  styleUrls: ['./faq.component.css'],
  animations: [
    trigger('expandCollapse', [
      state('open', style({ height: '*' })),
      state('closed', style({ height: 0, padding: 0, margin: 0, overflow: 'hidden' })),
      transition('open <=> closed', animate('500ms ease-in-out'))
    ])
  ]
})
export class FaqComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  faqItems: any = [
    { question: 'What is the Global Child Prodigy Awards initiative?', answer: 'The Global Child Prodigy Awards (GCP Awards) is a unique initiative that recognizes, appreciates, and rewards the Child Prodigies from around the world each year. It aims to identify young talents from various fields who demonstrate exceptional skills in areas such as academics, arts, sports, and innovation. These extraordinary children are honored at the Global Child Prodigy Award Ceremony, graced by prominent leaders and celebrities. Additionally, their inspiring stories are featured in the Global Child Prodigy Annual Book, which is circulated worldwide, showcasing their achievements and providing them with global exposure.', showAnswer: false },
    { question: 'Who is a Child Prodigy?', answer: 'A child prodigy is defined as someone who possesses exceptional talent or understanding far beyond their age group. These talented children typically exhibit extraordinary skills, knowledge, or abilities in one or more fields before the age of 15. They often achieve significant accomplishments or receive notable recognition for their talents at a young age.', showAnswer: false },
    { question: 'Why was the Global Child Prodigy Awards created?', answer: 'The Global Child Prodigy Awards were created to highlight the natural abilities of children who showcase unique and rare talents across the globe. The initiative\'s goal is to provide young talents with global exposure, helping them receive the recognition they deserve and connecting them with the right opportunities to create a significant impact on society. By supporting and encouraging these prodigies, the awards aim to ensure that they continue to excel without any obstacles in their journey.', showAnswer: false },
    { question: 'What are the eligibility criteria for the Global Child Prodigy Awards?', answer: 'The eligibility criteria for the Global Child Prodigy Awards include:Age Requirement: Applicants must be under 15 years of age at the time of application, Area of Talent: Applicants must demonstrate talent and passion in any field, such as academics, arts, sports, innovation, and more. For more please have a look at https://gcpawards.com/how-it-works', showAnswer: false },
    { question: 'Is there an age limit for participants?', answer: 'Yes, participants must be under 15 years of age at the time of application while applying for Global Child Prodigy Awards.', showAnswer: false },
    { question: 'Can children from any country apply for the awards?', answer: 'Yes, children from any country recognized by the United Nations are welcome to apply.', showAnswer: false },
    { question: 'Are there specific fields or categories in which a child can apply?', answer: 'Children can apply in a wide range of fields and categories, such as Acting & Theatre, Art, Cooking, Dance, Education, Entrainment, Entrepreneurship, Fashion, Gaming, Innovation & Technology, Intelligence & Memory - IQ, Language, Magician, Mentoring & Teaching, Music & Singing, Photography, Public Speaker & Presenter, Social & Environment, Space Science & Astronomy, Sports, Writing & Poetry, Yoga & Fitness, Social Media Influencer, and others.', showAnswer: false },
    { question: 'How do I apply for the Global Child Prodigy Awards?', answer: 'To apply for the Global Child Prodigy Awards Visit the official website at https://gcpawards.com/Registration and fill out the online application form, providing all required personal details, contact information, and a description of your talent. Submit your application before the specified deadline.', showAnswer: false },
    { question: 'Is there an application fee?', answer: 'There is a one-time application fee of USD $15 or INR 1250/- to avoid spam entries. This fee includes applicable government taxes. GCP charges only a one-time nominal application fee during the application process; there are no hidden fees. Beware of any organization or person claiming to be from GCP and seeking money from participants.', showAnswer: false },
    { question: 'Why does the Global Child Prodigy Awards charge an application fee?', answer: 'The Global Child Prodigy Awards (GCP) asks for a small application fee to make sure the process runs smoothly and fairly for everyone involved. Here\'s why this fee is essential: Keeping things real: The fee helps us make sure that only those who are genuinely passionate about showcasing their talents apply, and it keeps spam entries at bay. Covering our costs: We use the application fee to manage the expenses that come with reviewing applications, keeping our website running, server costs and others. It helps us continue to celebrate and support child prodigies worldwide. Ensuring fairness: By charging a nominal fee, we create an equal opportunity for all participants, as they are assessed based on their talents and not their financial capacity. Supporting our mission: The fee helps us maintain and grow the GCP Awards initiative, allowing us to keep recognizing and nurturing young talents across the globe. Remember, we only charge a one-time application fee and there are no hidden costs. If anyone claims to be from GCP and asks for extra money, please report them to us.', showAnswer: false },
    { question: 'I have received an email from GCPA that I have to pay extra money?', answer: 'It is essential to be aware that the Global Child Prodigy Awards only charges a one-time nominal application fee, as mentioned above. We do not ask for any additional fees for the award. It is possible that the email you received is from another organization or an individual attempting to impersonate GCP Awards. We advise you to exercise caution and only trust communications from official GCP Awards email addresses (i.e., ending with @gcpawards.com or @gcpawards.org). If you have any concerns or questions, please do not hesitate to reach out to us directly at info@gcpawards.com.', showAnswer: false },
    { question: 'When is the deadline for submitting applications?', answer: 'The deadline for submitting applications varies each year. The last date will be updated shortly.', showAnswer: false },
    { question: 'What information and documents should I include in the application?', answer: 'In your application, provide personal details, contact information, and a description of your talent, achievements, and contributions in your chosen field. You may also submit optional supporting evidence of your work, awards, or recognition on a national or international level, including but not limited to images, videos, resumes/CVs, certificates, honors, media coverage, or others', showAnswer: false },
    { question: 'Can I submit my application in a language other than English?', answer: 'Yes, any language is acceptable for communication during the selection and subsequent events. However, providing information in English can facilitate the evaluation process.', showAnswer: false },
    { question: 'Can I edit my application after submission?', answer: 'Once the online application has been submitted, participants can update or add more details, works, videos, photos, and other documents by navigating to "My Profile" on the website and including the necessary information. You can keep adding information to the online portal until the GCPA Application deadline is over. Providing comprehensive and relevant information can enhance the applicant\'s chances of being recognized and selected as a finalist.', showAnswer: false },
    { question: 'What if I encounter technical issues during the application process?', answer: 'If you experience technical issues during the application process, contact the GCP Awards team for assistance by writing to them at info@gcpawards.com. They will be able to help resolve any issues or provide guidance on completing your application.', showAnswer: false },
    { question: 'How many winners will be chosen each year?', answer: 'The Global Child Prodigy Awards selects 100 winners each year from various fields and categories.', showAnswer: false },
    { question: 'Can a participant apply in more than one category?', answer: 'A participant may submit their information in no more than one category per application. To participate in more than one category, participants are required to submit a separate application for each category.', showAnswer: false },
    { question: 'Will applicants receive feedback on their submissions?', answer: 'While the GCP Awards may not be able to provide individual feedback on every submission due to the high volume of applications, they do provide general guidance and updates on the selection process through their website and social media channels.', showAnswer: false },
    { question: 'When and where is the GCP Awards ceremony held?', answer: 'The GCP Awards ceremony\'s date and location vary each year. We will update the information soon as per confirmation.', showAnswer: false },
    { question: 'How are winners announced and informed?', answer: 'Winners are announced through the GCP Awards website, social media channels, and official press releases. Additionally, winners are informed individually via email.', showAnswer: false },
    { question: 'What is the purpose of the Global Child Prodigy Annual Book?', answer: 'The Global Child Prodigy Annual Book aims to showcase the extraordinary stories of the world\'s child prodigies. By featuring their achievements, the book provides these young talents with global exposure, inspiring others to pursue their passions and make a difference in the world.', showAnswer: false },
    { question: 'How can I obtain a copy of the Global Child Prodigy Annual Book?', answer: 'You can order a copy of the Global Child Prodigy Annual Book through the GCP official website or on Amazon', showAnswer: false },
    { question: 'How can I learn more about previous GCP Awards ceremonies?', answer: 'To learn more about past GCP Awards ceremonies, visit the GCP Awards website at https://gcpawards.com/gcpa2022 or follow our social media channels for updates, photos, and videos of previous events.', showAnswer: false },
    { question: 'Who are some of the notable guests from past GCP Awards events?', answer: 'Notable guests from past GCP Awards events include Nobel Peace Laureate Shri Kailash Satyarthi, Dr. Kiran Bedi (Honorable Lt. Governor of Puducherry), His Highness Sheikh Nahayan Mabarak Al Nahayan (Cabinet Member and Minister of Tolerance & Coexistence, Government of the UAE), Nobel Prize Winner Sir Richard J. Roberts, and Dr. Azad Moopen (Chairman and Managing Director - Aster DM Healthcare).', showAnswer: false },
    { question: 'How can I stay updated on GCP Awards news and announcements?', answer: 'To stay updated on GCP Awards news and announcements, follow our website and social media channels, and subscribe to our newsletter.', showAnswer: false },
    { question: 'Are there volunteer or partnership opportunities available with the GCP Awards?', answer: 'To inquire about volunteer or partnership opportunities with the GCP Awards, write to us at info@gcpawards.com.', showAnswer: false },
    { question: 'Can I nominate someone for the awards do they need to apply themselves?', answer: 'You can nominate someone for the Global Child Prodigy Awards by visiting https://gcpawards.com/nominate and submitting the nominee\'s information. The nominee can also apply directly by completing the online application form on the GCP Awards website.', showAnswer: false },
    { question: 'How do I contact the GCP Awards team for more information or assistance?', answer: 'If you require more information or assistance, you can contact the GCP Awards team by writing to them at info@gcpawards.com.', showAnswer: false },
    { question: 'How can I get involved with the Global Child Prodigy Awards community?', answer: 'You can get involved with the Global Child Prodigy Awards community by following our social media channels, participating in our events, engaging with our content, and sharing the inspiring stories of child prodigies with your network.', showAnswer: false },
    { question: 'Are there any success stories of previous winners?', answer: 'Yes, many previous GCP Awards winners have gone on to achieve great success in their respective fields, gaining further recognition, accolades, and opportunities. The GCP Awards website and social media channels often feature updates on the achievements and success stories of past winners.', showAnswer: false },
    { question: 'Can a participant win the award more than once?', answer: 'Yes, it is possible. If a participant continues to demonstrate exceptional talent, achievements, and impact in their field, they may be considered for the award again in the future.', showAnswer: false },
    { question: 'Is Global Child Prodigy available on WhatsApp?', answer: 'Yes, Global Child Prodigy Awards is accessible on WhatsApp. You can reach out to us at the following number: +91 86991 06991. Feel free to contact us if you have any questions or need assistance related to the GCP Awards.', showAnswer: false },
    { question: 'Is the Global Child Prodigy available on Telegram?', answer: 'The Global Child Prodigy Awards can be found on Telegram. The following username, @Gcpabot, can be used to communicate with us here at GCPA. If you have any questions or require assistance in relation to the GCP Awards, please do not hesitate to get in touch with us.', showAnswer: false },
    { question: 'On which social media platforms is GCPA available?', answer: 'Global Child Prodigy Awards (GCPA) maintains an active presence on a variety of social media platforms to engage with its audience and share updates. You can find GCPA on YouTube, Facebook, Instagram, Twitter, Pinterest, Spotify, Gaana, Amazon Music, JioSaavn, WhatsApp, & Telegram.', showAnswer: false }
  ];

  toggleAnswer(faqItem: any): void {
    this.faqItems.forEach((item:any) => {
      if (item === faqItem) {
        item.showAnswer = !item.showAnswer;
      } else {
        item.showAnswer = false;
      }
    });
  }

}
